version: '3.8'

services:
  app:
    container_name: app
    build:
      context: ./app
    depends_on:
      - db
    volumes:
      - ./src/:/app
      - ./app/php.ini:/usr/local/etc/php/php.ini

  db:
    container_name: db
    build:
      context: ./db
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./db/initdb:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=password

  web:
    container_name: web
    build:
      context: ./web
    ports:
      - 8080:80
    depends_on:
      - app
    volumes:
      - ./src/:/app
      - ./web/default.conf:/etc/nginx/conf.d/default.conf

volumes:
  db-store: